name: flights_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC_NAME
    inputType: InputTopic
    description: the kafka topic from which we will retrieve th enriched flights data
    defaultValue: live_flights_with_weather
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: the consumer group to read the enrichedd live flights data
    defaultValue: live_flights_with_weather_consumer
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: whether or not we are running on live or historical mode (for training purposes)
    defaultValue: live
    required: true
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_API_KEY
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: the hopsworks online feature group where the live data will be stored
    defaultValue: live_flights_tracking_with_weather_data
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: the version of the feature group
    defaultValue: 1
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
