name: flights_producer
language: python
variables:
  - name: KAFKA_TOPIC_NAME
    inputType: OutputTopic
    description: kafka topic to produce live flights data from AviationEdge API
    defaultValue: live_flights
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: whether we are in live or historical mode
    defaultValue: live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
