name: flights_producer
language: python
buildContext: ./services/flights_producer
variables:
  - name: KAFKA_TOPIC_NAME
    inputType: OutputTopic
    description: kafka topic to produce live flights data from AviationEdge API
    defaultValue: live_flights
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: whether we are in live or historical mode
    defaultValue: live
    required: true
  - name: AVIATION_EDGE_API_KEY
    inputType: Secret
    description: ''
    defaultValue: AVIATION_EDGE_API_KEY
    required: true
  - name: days
    inputType: FreeText
    description: the number of days to fetch flights data for whenever we are in historical mode
    defaultValue: 1
    required: false
files:
  - ./airlines.csv
  - ./airports.csv
  - ./FAA_aircraft_characteristics_database.xlsx
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
