name: flights_with_weather
language: python
variables:
  - name: KAFKA_INPUT_TOPIC_NAME
    inputType: InputTopic
    description: the kafka topic from where we will read flights data
    defaultValue: live_flights
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: the consumer group to read live flights data
    defaultValue: live_flights_consumer
    required: true
  - name: KAFKA_OUTPUT_TOPIC_NAME
    inputType: OutputTopic
    description: the new kafka topic where we will produce the enriched flights data (with weather data)
    defaultValue: live_flights_with_weather
    required: true
  - name: METEOMATICS_USERNAME
    inputType: Secret
    description: ''
    defaultValue: METEOMATICS_USERNAME
    required: true
dockerfile: dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
