name: contrail_predictor
language: python
variables:
  - name: KAFKA_TOPIC_NAME
    inputType: InputTopic
    description: we need to read from the live fligts weather data in orer to retrieve the primary keys of the flights
    defaultValue: live_flights_with_weather
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: consumer group to get primary keys
    defaultValue: live_flights_with_weather_consumer_primary_keys
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: always in live mode here because primary keys are only required for reading from the online feature store
    defaultValue: live
    required: true
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_API_KEY
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: hopsworks feature group
    defaultValue: live_flights_tracking_with_weather_data
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: hopsworks feature group version
    defaultValue: 1
    required: true
  - name: FEATURE_VIEW_NAME
    inputType: FreeText
    description: hopsworks feature view for data reading
    defaultValue: live_flights_tracking_with_weather_view
    required: true
  - name: FEATURE_VIEW_VERSION
    inputType: FreeText
    description: hopsworks feature view version
    defaultValue: 1
    required: true
  - name: LAST_N_MINUTES
    inputType: FreeText
    description: the window of seconds for which we want to retrieve live data from the online feature group
    defaultValue: 60
    required: true
dockerfile: dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
